// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text.Json.Serialization;
using Microsoft.EntityFrameworkCore;

namespace StreamingAPI.Models;

[Table("Conteudo")]


public class Conteudo
{
    public int Id { get; set; }
    public string Nome { get; set; }
    public string Tipo { get; set; }

    [MaxLength(300)]
    public string Url { get; set; }

    public int CriadorID { get; set; }

    [ForeignKey("CriadorID")]
    public Criador Criador { get; set; }

    public ICollection<ItemPlaylist> ItensPlaylist { get; set; }
}