// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text.Json.Serialization;
using Microsoft.EntityFrameworkCore;

namespace StreamingAPI.Models;

[Table("Criador")]
public class Criador
{
    public int Id { get; set; }
    public string Nome { get; set; }

    public List<Conteudo> Conteudos { get; set; } // Navegação reversa (opcional)
}