// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace StreamingAPI.Models;
[Table("Playlist")]
public class Playlist
{
    [Key]
    public int Id { get; set; }
    public string Nome { get; set; }

    // Relações
    public int UsuarioId { get; set; }
    //public int PlaylistID { get; set; }
    public Usuario Usuario { get; set; }
    public ICollection<ItemPlaylist> ItensPlaylist { get; set; }

}