// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace StreamingAPI.Models;

public class Usuario
{
    public Usuario() { }
    public int Id { get; private set; }
    public string Nome { get; private set; }
    public string Email { get; private set; }
    public byte[] PasswordHash { get; set; }
    public byte[] PasswordSalt { get; set; }
    public int Admin { get; set; } // 0 = usuário comum, 1 = admin
    public List<Playlist> Playlists { get; set; } // Relação 1:N

    public Usuario(/*int id, */string nome, string email)
    {
        Nome = nome;
        Email = email;
    }

    public void AlterarSenha(byte[] passwordHash, byte[] passwordSalt)
    {
        PasswordHash = passwordHash;
        PasswordSalt = passwordSalt;
    }

    //TOKEN DE USUARIO
    public class UserToken
    {
        public string Token { get; set; }
    }
    public void AlterarNome(string nome)
    {
        Nome = nome;
    }
    public void AlterarEmail(string email)
    {
        Email = email;
    }
}